# Source: keycloak/templates/db-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db
  labels:
    app: keycloak
    chart: keycloak-3.4.0
    heritage: Tiller
    release: keycloak
type: Opaque
data:
  password: cGFzc3dvcmQ= #password
---
# Source: keycloak/templates/keycloak-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-http
  labels:
    app: keycloak
    chart: keycloak-3.4.0
    release: "keycloak"
    heritage: "Tiller"
type: Opaque
data:
  password: cGFzc3dvcmQ= #password